import fs from 'node:fs';
import path from 'node:path';
const reference = 'https://moments.xocoweb.workers.dev';
const origin = (process.env.SITE_URL || 'http://localhost:4321').replace(/\/$/, '');
// The sitemap is generated by @astrojs/sitemap with SITE_URL already; only these static files need the origin.
for (const name of ['robots.txt', 'site.webmanifest']) {
  const file = path.resolve('dist', name);
  if (fs.existsSync(file)) fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replaceAll(reference, origin));
}
// src/pages/404.astro builds dist/404.html (served by hosts for unknown URLs); keep /404/ too.
const errorPage = path.resolve('dist/404.html');
if (fs.existsSync(errorPage)) {
  fs.mkdirSync(path.resolve('dist/404'), { recursive: true });
  fs.copyFileSync(errorPage, path.resolve('dist/404/index.html'));
}
